#!/usr/bin/env python3
"""Generate poems.js with all 80 poems."""
import json

def q(question, options, answer, explanation):
    return {"q": question, "options": options, "answer": answer, "explanation": explanation}

poems = [
    {"id": 1, "category": "solar", "season": "春季", "term": "立春", "poem": "立春偶成", "author": "张栻", "dynasty": "宋",
     "content": "律回岁晚冰霜少，春到人间草木知。\n便觉眼前生意满，东风吹水绿参差。",
     "translation": "冰雪消融，春天降临人间，草木最先感知春的气息。",
     "authorIntro": "张栻（1133-1189），字敬夫，号南轩，南宋理学家。",
     "background": "这首诗是张栻在立春时节所作。",
     "imagePrompt": "Chinese ink wash painting spring scenery green grass melting ice",
     "quizzes": [q("这首诗描写的是哪个节气的景象？", ["立春", "雨水", "春分", "惊蛰"], 0, "诗题就是《立春偶成》。"), q("诗人从哪种自然事物最先感受到春意？", ["花朵", "鸟鸣", "草木", "河流"], 2, "春到人间草木知。"), q("参差在诗中是什么意思？", ["长短不一", "碧绿如玉", "波光粼粼", "水流缓慢"], 0, "参差形容水面波纹长短不一。")]},
    {"id": 2, "category": "solar", "season": "春季", "term": "立春", "poem": "咏柳", "author": "贺知章", "dynasty": "唐",
     "content": "碧玉妆成一树高，万条垂下绿丝绦。\n不知细叶谁裁出，二月春风似剪刀。",
     "translation": "柳树如同碧玉妆扮一般高耸，垂下的枝条像万条绿色的丝带。二月的春风就像剪刀。",
     "authorIntro": "贺知章（659-744），字季真，唐代著名诗人。",
     "background": "这首诗是贺知章的代表作，二月春风似剪刀成为千古名句。",
     "imagePrompt": "Chinese painting willow tree drooping green branches tender leaves spring",
     "quizzes": [q("万条垂下绿丝绦把柳枝比喻成了什么？", ["绿丝带", "绿丝绦", "绿瀑布", "绿丝线"], 1, "绦是古代的一种丝织腰带。"), q("诗人说春风像什么？", ["温暖的手", "剪刀", "画笔", "扇子"], 1, "二月春风似剪刀是千古名句。"), q("这首诗描写的是哪个季节的柳树？", ["深秋", "初冬", "早春", "盛夏"], 2, "二月正是早春时节。")]},
    {"id": 3, "category": "solar", "season": "春季", "term": "雨水", "poem": "春夜喜雨", "author": "杜甫", "dynasty": "唐",
     "content": "好雨知时节，当春乃发生。\n随风潜入夜，润物细无声。\n野径云俱黑，江船火独明。\n晓看红湿处，花重锦官城。",
     "translation": "好的雨知道适应季节，春天来临就及时落下。随风在夜里悄悄来到，滋润万物轻柔无声。",
     "authorIntro": "杜甫（712-770），字子美，号少陵野老，唐代伟大的现实主义诗人，与李白合称李杜。",
     "background": "这首诗是杜甫在成都草堂时所作，描写了春夜降雨的景象。",
     "imagePrompt": "Chinese landscape spring night rain gentle rain small boat with lantern misty fields",
     "quizzes": [q("这首诗中的好雨是在什么季节下的？", ["夏", "秋", "春", "冬"], 2, "当春乃发生。"), q("杜甫用什么词形容雨润物的方式？", ["哗哗", "滴滴", "细无声", "纷纷"], 2, "润物细无声。"), q("诗中描写锦官城的什么景象？", ["雪景", "红湿的花", "绿草", "落叶"], 1, "晓看红湿处，花重锦官城。")]},
    {"id": 4, "category": "solar", "season": "春季", "term": "雨水", "poem": "绝句", "author": "杜甫", "dynasty": "唐",
     "content": "迟日江山丽，春风花草香。\n泥融飞燕子，沙暖睡鸳鸯。",
     "translation": "春天的太阳照耀，春风送来花草的芬芳。泥土松软，燕子忙着衔泥筑巢，沙滩被阳光晒暖，鸳鸯在沙上安睡。",
     "authorIntro": "杜甫（712-770），唐代伟大的现实主义诗人。",
     "background": "这首诗写于杜甫居成都草堂期间，以明快欢畅的笔调描绘了春天明媚的自然风光。",
     "imagePrompt": "spring countryside sunshine swallows mandarin ducks on warm sand blossoming flowers",
     "quizzes": [q("这首诗描写的是什么季节？", ["秋天", "夏天", "春天", "冬天"], 2, "春风花草香和泥融飞燕子都是典型的春日景象。"), q("诗中哪种动物在衔泥筑巢？", ["鸳鸯", "燕子", "黄鹂", "杜鹃"], 1, "泥融飞燕子。"), q("迟日在诗中是什么意思？", ["迟到", "春天的太阳", "缓慢", "迟暮"], 1, "迟日是春天的太阳。")]},
    {"id": 5, "category": "solar", "season": "春季", "term": "惊蛰", "poem": "观田家", "author": "韦应物", "dynasty": "唐",
     "content": "微雨众卉新，一雷惊蛰始。\n田家几日闲，耕种从此起。",
     "translation": "细雨滋润，百花更新，一声春雷惊醒了蛰伏的虫儿。农家从惊蛰开始就要忙于耕种了。",
     "authorIntro": "韦应物（737-792），唐代诗人，世称韦苏州。",
     "background": "这首诗描写了惊蛰时节的农村景象，春雷响动，细雨润物，农忙时节开始了。",
     "imagePrompt": "early spring thunderstorm farmers working in paddy fields new sprouts emerging",
     "quizzes": [q("一雷惊醒了什么？", ["花朵", "蛰虫", "动物", "人们"], 1, "惊蛰是二十四节气之一，春雷惊醒冬眠的虫豸。"), q("农家的繁忙是从哪个节气开始的？", ["立春", "春分", "惊蛰", "清明"], 2, "田家几日闲，耕种从此起说明惊蛰一到，农忙就开始了。"), q("微雨滋润了什么？", ["山川", "众卉", "河流", "房屋"], 1, "微雨众卉新说明细雨滋润了百花。")]},
    {"id": 6, "category": "solar", "season": "春季", "term": "惊蛰", "poem": "新雷", "author": "张维屏", "dynasty": "清",
     "content": "造物无言却有情，每于寒尽觉春生。\n千红万紫安排著，只待新雷第一声。",
     "translation": "大自然虽然不说话却充满情意，每当寒冬将尽便感到春天的萌动。万紫千红的花朵已安排就绪，只等待新雷。",
     "authorIntro": "张维屏（1780-1859），字子树，号南山，清代著名诗人。",
     "background": "这首诗以新雷为题，表达了诗人对春天的期盼和喜悦。",
     "imagePrompt": "first spring thunder dark clouds lightning bolt flower buds about to bloom",
     "quizzes": [q("诗人说造物有什么特点？", ["有言有情", "无言有情", "有言无情", "无言无情"], 1, "造物无言却有情是大自然的拟人化。"), q("花朵们在等待什么？", ["春雨", "春风", "新雷第一声", "阳光"], 2, "千红万紫安排著，只待新雷第一声。"), q("这首诗写于什么时节？", ["秋末", "冬末春初", "夏初", "春末"], 1, "每于寒尽觉春生。")]},
    {"id": 7, "category": "solar", "season": "春季", "term": "春分", "poem": "春分日", "author": "徐铉", "dynasty": "唐",
     "content": "仲春初四日，春色正中分。\n绿野徘徊月，晴天断续云。\n燕飞犹个个，花落已纷纷。\n思妇高楼晚，歌声不可闻。",
     "translation": "仲春初四，春色正好平分。燕子成双成对地飞翔，花瓣纷纷飘落。思念丈夫的妇人在傍晚登上高楼。",
     "authorIntro": "徐铉（917-992），字鼎臣，五代至北宋初年著名文学家。",
     "background": "这首诗描写春分时节的景色，昼夜平分，春色正浓，同时流露出淡淡的离愁。",
     "imagePrompt": "spring equinox blooming flowers swallows flying petals falling poetic",
     "quizzes": [q("春色正中分说的是哪个节气的特点？", ["立春", "春分", "清明", "谷雨"], 1, "春分这一天昼夜平分，正好是春色正中分。"), q("诗中描写了什么动物在飞翔？", ["黄鹂", "燕子", "大雁", "白鹭"], 1, "燕飞犹个个描写燕子成双成对地飞翔。"), q("思妇高楼晚表达了什么情感？", ["欢乐", "思乡/思念亲人", "忧愁", "愤怒"], 1, "思妇指思念丈夫的妇人，流露出深深的思念之情。")]},
    {"id": 8, "category": "solar", "season": "春季", "term": "春分", "poem": "村居", "author": "高鼎", "dynasty": "清",
     "content": "草长莺飞二月天，拂堤杨柳醉春烟。\n儿童散学归来早，忙趁东风放纸鸢。",
     "translation": "农历二月，青草茂盛，黄莺飞舞，杨柳轻轻拂过堤岸。孩子们放学回来，赶紧趁着东风去放风筝。",
     "authorIntro": "高鼎，清代诗人，这首《村居》是其最著名的作品。",
     "background": "这首诗写于农历二月，以生动的笔触描绘了春日乡村的美好景象和儿童放风筝的欢乐场景。",
     "imagePrompt": "spring countryside village children flying kites colorful kites in blue sky",
     "quizzes": [q("诗中孩子们在做什么？", ["捉迷藏", "放风筝", "钓鱼", "踢足球"], 1, "忙趁东风放纸鸢说明孩子们趁着东风放风筝，纸鸢就是风筝。"), q("杨柳在做什么？", ["落叶", "开花", "拂堤", "干枯"], 2, "拂堤杨柳形容杨柳的枝条轻轻拂过堤岸。"), q("这首诗描写的是农历几月？", ["正月", "二月", "三月", "四月"], 1, "草长莺飞二月天明确说明是农历二月。")]},
    {"id": 9, "category": "solar", "season": "春季", "term": "清明", "poem": "清明", "author": "杜牧", "dynasty": "唐",
     "content": "清明时节雨纷纷，路上行人欲断魂。\n借问酒家何处有，牧童遥指杏花村。",
     "translation": "清明时节，细雨纷纷飘落，路上扫墓的人们悲伤得好像丢了魂。牧童远远地指着杏花盛开的村庄。",
     "authorIntro": "杜牧（803-852），字牧之，晚唐著名诗人，与李商隐并称小李杜。",
     "background": "这首诗是杜牧描写清明节的最著名作品，情景交融，既写了清明的凄迷雨景，又表现了行人的愁绪。",
     "imagePrompt": "Qingming Festival soft rain ancient road travelers apricot blossom village",
     "quizzes": [q("清明时节天气如何？", ["晴朗", "雨纷纷", "下雪", "炎热"], 1, "清明时节雨纷纷是千古名句。"), q("路上的行人为什么欲断魂？", ["太高兴", "悲伤愁绪", "迷路", "赶路"], 1, "清明是祭祖扫墓的节日，人们思念已故亲人，所以悲伤得欲断魂。"), q("牧童指向的是什么地方？", ["桃花村", "杏花村", "梅花村", "梨花村"], 1, "牧童遥指杏花村是千古名句，牧童指向的是杏花盛开的村庄。")]},
    {"id": 10, "category": "solar", "season": "春季", "term": "清明", "poem": "寒食", "author": "韩翃", "dynasty": "唐",
     "content": "春城无处不飞花，寒食东风御柳斜。\n日暮汉宫传蜡烛，轻烟散入五侯家。",
     "translation": "春天的长安城处处飘落花瓣，寒食节的东风吹斜了宫中的杨柳。傍晚皇宫传送蜡烛赏赐权贵。",
     "authorIntro": "韩翃，字君平，唐代大历十才子之一。这首《寒食》是他最著名的作品。",
     "background": "寒食节在清明前一或两天，是纪念介子推的节日，这天禁火。韩翃的这首诗讽刺了皇宫权贵的特权。",
     "imagePrompt": "Tang Dynasty capital Chang an city flower petals palace willows royal palace",
     "quizzes": [q("春城指的是哪座城市？", ["洛阳", "开封", "长安", "北京"], 2, "长安是唐朝的都城，春城无处不飞花描写的是唐朝长安城春日飞花的景象。"), q("寒食节这天有什么习俗？", ["放鞭炮", "禁火", "赛龙舟", "赏月"], 1, "寒食节在清明前一两天，这天要禁火，只吃冷食，是纪念介子推的节日。"), q("诗中五侯指什么人？", ["五个猎人", "五个侯爵权贵", "五个农民", "五个诗人"], 1, "五侯指受皇帝恩宠的贵族。")]}
]

# Write to file
with open('/workspace/poem-learning/src/data/poems_extra.json', 'w', encoding='utf-8') as f:
    json.dump(poems, f, ensure_ascii=False, indent=2)
print(f"Written {len(poems)} poems to poems_extra.json")
